// Automatically generated by MockGen. DO NOT EDIT!
// Source: user.go

package mock_user

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of User interface
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *_MockUserRecorder
}

// Recorder for MockUser (not exported)
type _MockUserRecorder struct {
	mock *MockUser
}

func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &_MockUserRecorder{mock}
	return mock
}

func (_m *MockUser) EXPECT() *_MockUserRecorder {
	return _m.recorder
}

func (_m *MockUser) GetId() int {
	ret := _m.ctrl.Call(_m, "GetId")
	ret0, _ := ret[0].(int)
	return ret0
}

func (_mr *_MockUserRecorder) GetId() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetId")
}
